apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iobroker-pv-claim
  labels:
    {{- include "iobroker.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi