apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iobroker
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: iobroker
    repoURL: https://jochenrichter.github.io/kubernetes-at-home/
    targetRevision: 1.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
